A = int(input())
B = int(input())
C = int(input())
D = list(str(A*B*C))
print(D.count('0'))
print(D.count('1'))
print(D.count('2'))
print(D.count('3'))
print(D.count('4'))
print(D.count('5'))
print(D.count('6'))
print(D.count('7'))
print(D.count('8'))
print(D.count('9'))